version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Cyber@1234
      - DB=SecurityScanResult
    depends_on:
      - db
  dashboard:
    build: ./dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Cyber@1234"
      ACCEPT_EULA: "Y"
    volumes:
      - dbdata:/var/opt/mssql/data
volumes:
  dbdata:
